spring:
  datasource:
    url: jdbc:postgresql://135.181.250.34:15432/sctapi
    username: postgres
    password: 2dc61064f9916a420d53
  liquibase:
    change-log: classpath:config/liquibase/master.xml