version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: seubanco
      POSTGRES_USER: seuusuario
      POSTGRES_PASSWORD: suasenha
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
