services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta para o protocolo AMQP
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin  # Usuário padrãol
      RABBITMQ_DEFAULT_PASS: admin  # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados
      - rabbitmq_logs:/var/log/rabbitmq  # Persistência de logs

volumes:
  rabbitmq_data:
  rabbitmq_logs:
