spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: user01
    password: password
  liquibase:
    change-log: classpath:config/liquibase/master.xml

logging:
  level:
    org.springframework.web: DEBUG