server:
  port: 8082
  servlet:
    context-path: /order-update-db

spring:
  jpa:
    hibernate:
      ddl-auto: none
      jdbc.time_zone: America/Sao_Paulo
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker}
    
management:
  endpoint:
    health:
      show-details: always # Mostra os detalhes dos componentes no /health
  endpoints:
    web:
      exposure:
        include: health, info # Garante que /actuator/health está acessível